# Generated by Django 4.2.2 on 2023-07-16 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('experience', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('pin', models.CharField(max_length=6)),
                ('f_status', models.CharField(default='Pending', max_length=30)),
                ('f_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
