# Generated by Django 4.2.2 on 2023-07-17 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist_app.category')),
                ('freelancer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist_app.freelancerreg')),
            ],
        ),
    ]
