# Generated by Django 4.2.2 on 2023-07-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0004_freelancer_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerreg',
            name='categories',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Freelancer_categories',
        ),
    ]
