# Generated by Django 4.2.2 on 2023-07-17 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0006_remove_freelancerreg_categories_freelancercategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pimage', models.ImageField(upload_to='')),
                ('pname', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('p_size', models.CharField(max_length=30)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist_app.category')),
                ('freelancer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist_app.freelancerreg')),
            ],
        ),
    ]
