# Generated by Django 4.2.2 on 2023-07-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0007_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
