# Generated by Django 4.2.2 on 2023-07-18 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0008_userreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='f_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
