# Generated by Django 4.2.2 on 2023-07-18 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0009_userreg_f_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreg',
            old_name='f_log',
            new_name='u_log',
        ),
    ]
