# Generated by Django 4.2.2 on 2023-07-18 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0011_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='u_log',
        ),
        migrations.AddField(
            model_name='cart',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artist_app.userreg'),
        ),
    ]
