# Generated by Django 4.2.2 on 2023-07-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0012_remove_cart_u_log_cart_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_status',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
