# Generated by Django 4.2.2 on 2023-07-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0014_cart_pay_type_cart_payment_date_cart_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
