# Generated by Django 4.2.2 on 2023-07-18 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0016_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='cart_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='feedback_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artist_app.feedback'),
        ),
    ]
