# Generated by Django 4.2.2 on 2023-07-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0017_remove_feedback_cart_id_cart_feedback_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
