# Generated by Django 4.2.2 on 2023-07-18 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0018_feedback_feedback_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artist_app.product'),
        ),
    ]
