# Generated by Django 4.2.2 on 2023-07-18 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0019_feedback_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requeststatus', models.CharField(default='Pending', max_length=30)),
                ('requestimage', models.ImageField(upload_to='')),
                ('requestname', models.CharField(max_length=30)),
                ('requestdesc', models.TextField()),
                ('requestsize', models.CharField(max_length=30)),
                ('freelancer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist_app.freelancerreg')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artist_app.userreg')),
            ],
        ),
    ]
