# Generated by Django 4.2.2 on 2023-07-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0020_requestproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestproduct',
            name='requestprice',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
