# Generated by Django 4.2.2 on 2023-07-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0021_requestproduct_requestprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userreg',
            name='district',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userreg',
            name='housename',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userreg',
            name='pin',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userreg',
            name='place',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
