# Generated by Django 4.2.2 on 2023-07-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0022_userreg_city_userreg_district_userreg_housename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prodstatus',
            field=models.CharField(default='Pending', max_length=30, null=True),
        ),
    ]
