# Generated by Django 4.2.2 on 2023-07-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0024_requestproduct_reqexpecteddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestproduct',
            name='reqcompletedate',
            field=models.DateField(null=True),
        ),
    ]
