# Generated by Django 4.2.2 on 2023-07-19 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0026_requestproduct_reqrequirestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestproduct',
            name='requestname',
        ),
    ]
