# Generated by Django 4.2.2 on 2023-07-19 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0027_remove_requestproduct_requestname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=30)),
                ('reply', models.CharField(max_length=30)),
                ('freelancer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist_app.freelancerreg')),
                ('request_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artist_app.requestproduct')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artist_app.userreg')),
            ],
        ),
    ]
