# Generated by Django 4.2.2 on 2023-07-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0028_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='reply',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
