# Generated by Django 4.2.2 on 2023-07-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0030_chat_reply_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
