# Generated by Django 4.2.2 on 2023-07-20 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0031_alter_chat_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='reply_status',
        ),
    ]
